# Generated by Django 2.1.7 on 2019-03-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('id_num', models.CharField(default='', max_length=200)),
                ('insur_num', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('tel_num', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
