# Generated by Django 2.1.7 on 2019-03-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='acc_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
