# Generated by Django 2.1.7 on 2019-03-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_account_acc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
